### ISSUE TITLE
you can just inspect the page to get access or just type the link in the search bar without password

### ISSUE THREAD

**Issue by Firetitan750** [Tumbleweed-64/Tumbleweed-64.github.io#2]
<sub>website pass no work</sub>
you can access the YT unblocker and other things without the password you just need to change the password in the inspector to something like 'a'. You can also just type the website then the html file to access without inspector. add this to the website to disable right click:
-- START --
// Disable right-click
document.addEventListener('contextmenu', (e) => e.preventDefault());

function ctrlShiftKey(e, keyCode) {
  return e.ctrlKey && e.shiftKey && e.keyCode === keyCode.charCodeAt(0);
}

document.onkeydown = (e) => {
  // Disable F12, Ctrl + Shift + I, Ctrl + Shift + J, Ctrl + U
  if (
    event.keyCode === 123 ||
    ctrlShiftKey(e, 'I') ||
    ctrlShiftKey(e, 'J') ||
    ctrlShiftKey(e, 'C') ||
    (e.ctrlKey && e.keyCode === 'U'.charCodeAt(0))
  )
    return false;
};
-- END --
to fix the website link being accessable without the password just make the website all in one html file then hide the current page and show the other page when the password is a success make sure the different pages are in divs with separate ID's then it should work. 
-lehsaD backwards

**Comment by Tumbleweed-64** [comment]
Oh, I know. the website is in beta, meaning security isn't exactly the best YET. I've been working on other things for now. I didn't disable right-clicking because kids at school can't inspect either way. I'm going to buff up the security script soon.

**Comment by Tumbleweed-64** [comment]
Bad answer. Good idea about divs though. I'm doing that for my new game that'll be out soon. I'll add the right-click disabler to it, but it might take a little while to move the code from the main page to index.html, however. I've been working on other things and meant to do something about it but didn't. ¯\_ (ツ)_/¯

**Comment by Tumbleweed-64** [comment]
added right-click disabling code to the security and am working on some security buffs rn (in my editor, not here) so I think some big things will be around the corner after I finish writing a few games. Right now I gotta:

- [ ] finish security buff
- [ ] complete both new games (dropping in some repos after release on-site)
- [ ] and delete some deadweight pages, such as the game one that doesn't work anymore because it relied on 3kho and its onrender counterparts.
